---
- name: Set up load balancer to use apache server
  ec2_elb_lb:
    name: "{{ env }}-lb"
    region: "{{ region }}"
    state: present
    subnets:
        - "{{ web_subnet1 }}"
        - "{{ web_subnet2 }}"
    security_group_ids: ["{{ web_sec_group.group_id }}"]
    listeners:
      - protocol: tcp
        load_balancer_port: 80
        instance_port: 80
      - protocol: tcp
        load_balancer_port: 443
        instance_port: 443
      - protocol: tcp
        load_balancer_port: 8080
        instance_port: 8080
    health_check:
        ping_protocol: tcp
        ping_port: 80
        response_timeout: 5
        interval: 30
        unhealthy_threshold: 2
        healthy_threshold: 10
    ignore_errors: yes

- name: Add Instance to Existing ELB
  local_action:
    module: ec2_elb
    region: "{{ region }}"
    ec2_elbs: "{{ elb_name }}"
    state: present
    #instance_id: "{{ ansible_ec2_instance_id }}"
    instance_id: "{{ item.id }}"
  with_items: ec2a.instances
    #- ec2b.instances
  ignore_errors: yes