---  
- name: Create the zone 4 Db2 server instances
  ec2:
    image: "{{ server.ec2_image }}"
    region: "{{ region }}"
    instance_type: "{{ server.instance_type }}"
    #assign_public_ip: True
    key_name: "{{key_name}}"
    group: ["{{ env}}-sg-Db-internal", "{{ env}}-vpc-ssh"]
    instance_tags: { Name: "{{ env }}-zone4-Db3", type: Dbserver, Stack: Ansible_Test, Owner: devops, tier: Db, App: mongodb02, env: "{{ env }}", az: 4 }
    exact_count: "{{ server.zone_1_count }}"
    count_tag: { type: Dbserver, env: "{{ env }}", az: 04 }
    vpc_subnet_id: "{{ db_subnet2}}"
    zone: "{{ zone_4 }}"
    wait: yes
  register: ec2d
    #tags: ec2

- name: Add Appserver instances to host group
    local_action: add_host hostname={{ item.private_ip }} groupname=db1
    with_items: ec2d.instances

- name: wait for the instance to start
    local_action: wait_for state=started host={{ item.private_ip }} port=22 search_regex=OpenSSH
    with_items: ec2d.instances
    ignore_errors: yes

# - name: Giving another 65 secs to give stack to come up clean running status
#   wait_for: port=22 delay=65
#   ignore_errors: yes