---
- name: Create Web security group
  ec2_group:
    name: "{{ env }}-sg-web"
    region: "{{ region }}"
    description: allow web access from everywhere
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ control_ip}}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
    register: web_sec_group