---  
- name: Create the zone 1 web1 server instances
  ec2:
    image: "{{ server.ec2_image }}"
    region: "{{ region }}"
    instance_type: "{{ server.instance_type }}"
    #assign_public_ip: True
    key_name: "{{key_name}}"
    group: ["{{ env}}-sg-web", "{{ env}}-vpc-ssh"]
    instance_tags: { Name: "{{ env }}-zone1-web1", type: webserver, Stack: Ansible_Test Owner: devops, tier: web, App: web01, env: "{{ env }}", az: 1 }
    exact_count: "{{ server.zone_1_count }}"
    count_tag: { type: webserver, env: "{{ env }}", az: 01 }
    vpc_subnet_id: "{{ web_subnet1 }}"
    zone: "{{ zone_1 }}"
    wait: yes
  register: ec2a

- name: Add Webserver instances to host group
    local_action: add_host hostname={{ item.private_ip }} groupname=web1
    with_items: ec2a.instances

- name: Wait for zone 1 web servers to be reachable via SSH
    wait_for: host={{ item.private_ip }} port=22 search_regex=OpenSSH
    with_items: ec2a.tagged_instances

- name: Getting Instance ID for ELB
    local_action: ec2_eip in_vpc=yes instance_id={{ item.id }} region={{ region }}
    local_action: ec2-instances in_vpc=yes instance_id={{ item.id }} region={{ region }}
    local_action: ec2_eip in_vpc=yes instance_id={{ item.id }} region={{ region }}
    with_items: ec2a.instances
    register: ec2a