---
- name: Create the zone 2 web2 server instances
  ec2:
    image: "{{ server.ec2_image }}"
    region: "{{ region }}"
    instance_type: "{{ server.instance_type }}"
    #assign_public_ip: False
    key_name: "{{key_name}}"
    group: ["{{ env}}-sg-web", "{{ env}}-vpc-ssh"]
    instance_tags: { Name: "{{ env }}-zone2-web2", type: webserver, Stack: Ansible_Test, Owner: devops, tier: web, App: web02, env: "{{ env }}", az: 2 }
    exact_count: "{{ server.zone_2_count }}"
    count_tag: { type: webserver, env: "{{ env }}", az: 02 }
    vpc_subnet_id: "{{ web_subnet2 }}"
    zone: "{{ zone_2 }}"
    wait: yes
  register: ec2b

- name: Add Webserver instances to host group
   local_action: add_host hostname={{ item.private_ip }} groupname=web1
   with_items: ec2b.instances

  #- set_fact: var_hostname="{{ var_hostname }}"

- name: Wait for zone 1 web servers to be reachable via SSH
    wait_for: host={{ item.private_ip }} port=22 search_regex=OpenSSH
    with_items: ec2a.tagged_instances
    #when: item.public_dns_name is defined

  #- name: Getting Instance ID for ELB
    #local_action: ec2_eip in_vpc=yes instance_id={{ item.id }} region={{ region }}
    #local_action: in_vpc=yes instance_id={{ item.id }} region={{ region }}
    #with_items: ec2b.instances
    #register: ec2b
  #- debug: var=ec2a